### ISSUE TITLE
Add funtionallity for admin to edit the "Next Genre" tab on the webbsite.

### ISSUE THREAD

**Issue by microl44** [microl44/Julet#10]
Make it so the mysql root account on the host server can edit the Next Genre label and type in a genre/fetch genres from database (either text field where the admin can type in whatever they want, or a dropdown where genres are fetched from the database).

**Comment by microl44** [comment]
While you're at it, add styling to it as well :)

**Comment by beta9889** [comment]
> While you're at it, add styling to it as well :)

my boi 2 issues

**Comment by microl44** [comment]
Just do it god damnit

**Comment by microl44** [comment]
Code for "next genre" tab is gone for some reason, probably your fault. This issue will be closed and a new one will be opened.
